version: 0.2

phases:
  install:
    commands:
      - 'yum update -y'
      - 'yum install git -y'
    
  build:
    on-failure: ABORT
    commands:
      - "count=$(grep -w '<title>HealthCare Hospital</title>' index.html | wc -l)"
      - 'if [ $count -eq 0 ]; then
          echo "Title not found"; 
          BUILD_STATUS="failure";
          DESCRIPTION="Status Check Failed: Title not found"; 
          exit 1; 
        else
          echo "Title found";
          BUILD_STATUS="success";
          DESCRIPTION="Status Check Passed: Title found";
          exit 0;
        fi'

    finally:
      - 'COMMIT_SHA=$CODEBUILD_RESOLVED_SOURCE_VERSION'

    post_build:
      commands:
        - aws codepipeline put-job-failure-result --job-id $CODEBUILD_BUILD_ID --failure-details "{\"message\": \"Test Message\"}" --output text
